spring.application.name=worthmate
# -----------------------------
# SERVER CONFIG
# -----------------------------
server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# -----------------------------
# DATABASE CONFIG (PostgreSQL)
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/worthmate.ai
spring.datasource.username=postgres
spring.datasource.password=root5113
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -----------------------------
# JWT CONFIG
# -----------------------------
jwt.secret=CobuvHnfeuNjYIgTunAq9ufbtlVKKi2HJTS/nTm4n/U=
jwt.expiration=86400000

# -----------------------------
# LOGGING CONFIG
# -----------------------------
logging.level.org.springframework=INFO
logging.level.com.worthmate=DEBUG

# -----------------------------
# TIMEZONE
# -----------------------------
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dishantdrugkar4@gmail.com
spring.mail.password=iiei tere acxv zhkf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true